### ISSUE TITLE
Updated docker build  ubuntu 18.04 base

### ISSUE THREAD

**Issue by ukkathva** [rennu/dpg#13]
I have updated the docker build  with 18.04  versions with updated dependencies .
[Dockerfile.zip](https://github.com/rennu/dpg/files/4705248/Dockerfile.zip)

d

**Comment by rennu** [comment]
Hi,

I already had a Dockerfile for 18.04 prepared but then 20.04 happened. Thanks for reaching out!

(There are now files for 16.04, 18.04 and 20.04).

**Comment by ukkathva** [comment]
Thats Great, Is there any option of using merging mesh-room along with this pipeline? I have used meshroom which seems to be way faster as that use more of GPU.
