### ISSUE TITLE
Docker running without result

### ISSUE THREAD

**Issue by Uncle-Justice** [rennu/dpg#14]
when running "docker run -v /tmp/example:/datasets --rm -it spedenaave/dpg"
it returns "Missing some of mandatory parameters: --type, --input and --output". What's wrong with this?

**Comment by rennu** [comment]
Can you list all the commands you tried to run? Running `docker run -v /tmp/example:/datasets --rm -it spedenaave/dpg` will only create you a new container in which you can then run the pipeline.

**Comment by Uncle-Justice** [comment]
Environment : ubuntu16.04
I just pull the image from the hub and run 
`git clone https://github.com/openMVG/ImageDataset_SceauxCastle /tmp/example`
`docker run -v /tmp/example:/datasets --rm -it spedenaave/dpg`
It outputs 
`Missing some of mandatory parameters: --type, --input and --output`
`Use --help to see usage instructions`
Using`docker ps -a`, it shows no new container created.

Is it the OS version that caused the output?

**Comment by rennu** [comment]
I believe you have somehow ended up with an ancient version of the docker image. That image seems to have 1) entrypoint which the current one does not and 2) really old version of the pipeline script (and tools).

I recommend you remove the image (`docker rmi spedenaave/dpg` and then `docker image ls` to be sure it's gone) from your workstation and try downloading it again (`docker pull spedenaave/dpg:latest`).

If you are still having troubles, you could clone this repo and build the image by yourself. 

I ran the commands from the readme.md example on a clean ubuntu 16.04 server. Here's how it shoud look like:

![image](https://user-images.githubusercontent.com/2362509/88889408-ba1a8580-d248-11ea-9269-3244f8b488f7.png)

**Comment by Uncle-Justice** [comment]
Yes, I pulled the image again and it worked. I also got the similar meshlab result. 
Thank you so much:)

**Comment by rennu** [comment]
Great to hear!
