### ISSUE TITLE
I this repo useful for Run mvg and mvs faster ? 

### ISSUE THREAD

**Issue by SabraHashemi** [rennu/dpg#19]
I want to use mvs and mvg for dense and sparse ply reconstruction, so i have to go through mvs and mvg, but in between these two i had to write my data down then import it to another that this take so long time, so i should somehow make these progress in ram(without reading and writing) 
These repo can do this ?

**Comment by rennu** [comment]
So you wish to skip `openMVG_main_openMVG2openMVS` step? If so then no, it's not possible by using this repository.

**Comment by SabraHashemi** [comment]
> So you wish to skip `openMVG_main_openMVG2openMVS` step? If so then no, it's not possible by using this repository.

no, I wish to skip any writing and reading between these two or after them , when you write down a ply and then in the next stage read it again, it will cost much time, did you get what I mean?

**Comment by rennu** [comment]
I see. No, you can't skip writing and reading to disk between steps by using contents of this repo.

**Comment by SabraHashemi** [comment]
so what is blow command for? isn't this for running faster?
    openmvs = parser.add_argument_group("OpenMVS")
    openmvs.add_argument("--output-obj",
        action = "store_true",
        help = "Output mesh files as obj instead of ply")

**Comment by SabraHashemi** [comment]
and I wonder that why pipeline doesn't have command like `openMVG_main_PointsFiltering`

**Comment by rennu** [comment]
> so what is blow command for? isn't this for running faster? openmvs = parser.add_argument_group("OpenMVS") openmvs.add_argument("--output-obj", action = "store_true", help = "Output mesh files as obj instead of ply")

No, it's only for saving mesh files in obj format in openmvs instead of ply (default). I haven't done any testing on whether it's faster or slower.

> and I wonder that why pipeline doesn't have command like `openMVG_main_PointsFiltering`

I think point filtering was previously part of `openMVG_main_ComputeMatches` but apparently now is it's own binary.

I actually did some fixes yesterday because the pipeline.py was broken due to changes in openmvg pipeline and the fix includes `openMVG_main_PointsFiltering` step.

**Comment by SabraHashemi** [comment]
thanks, i checked your update and i got :
ERROR: [sequential_SfM.cpp:110] Unable to choose an initial pair, since there is no defined intrinsic data.
INFO: [sequential_SfM.cpp:173] Cannot find a valid initial pair - stop reconstruction.
Failed while executing: 
/opt/openmvg/bin/openMVG_main_SfM -s INCREMENTAL -i /datasets/output/matches/sfm_data.json -m /datasets/output/matches -o /datasets/output/reconstruction_global

**Comment by SabraHashemi** [comment]
i think this problem is related to sensor_width_camera_database.txt that doesn't contain configuration for most cameras, I can send you one to update if you want

**Comment by rennu** [comment]
You might want to take a look at the actual [openmvg repo](https://github.com/openMVG/openMVG) for that.
