### ISSUE TITLE
Raise meaningful error messages?

### ISSUE THREAD

**Issue by adrien-jacquot** [rennu/dpg#3]
Hello,

Thank you for this great piece of work, I never tried OpenMVG/MVS before but I was able to start using them in a few hours!

Depending on the dataset used I got some errors at different stages of the pipeline, some during the features matching and others during the mesh refinement or texture generation.

I was wondering if there was a plan to catch and raise more meaningful error messages, for now one can only see "Failed at step XXX".

Thanks!

**Comment by rennu** [comment]
Thanks for your nice words!

Yes, it would be nice to have meaningful messages. However, with the amount of things that could go wrong with the pipeline, I think it's better to just output OpenMVG & OpenMVS without trying to create a system to guess the reason for the error.
