### ISSUE TITLE
Error in constructing the dense point cloud

### ISSUE THREAD

**Issue by huikang** [rennu/dpg#9]
I created my own data set which are a sequence of images and run the pipeline. The error I got is

```
46      3
       47      4
       48      1
       49      2
       50      1
       51      1
       52      1
There is no defined intrinsic data in order to compute an essential matrix for the initial pair.
```

However, using the castle example images, it worked just fine. The only difference between my data set and the castle one is that I don't have the file `k.txt`. Does anyone know how to popular the k.txt file? Thanks.

**Comment by rennu** [comment]
K.txt is not needed. The error you are getting is better explained [here](https://github.com/openMVG/openMVG/issues/1218). In other words, it is not related to the pipeline.py but OpenMVG.

The purpose of the pipeline.py is to try to automate process of creating textured meshes from a set of images. For the actual reconstruction it uses OpenMVG and OpenMVS tools which are separate projects. When you receive an error that is not related to missing binaries or pipeline calling executables using incorrect command line arguments (this could happen if there's an update to either project that changes argument requirements), the best places for help would [OpenMVG](https://openmvg.readthedocs.io/en/latest/) and [OpenMVS](https://github.com/cdcseacave/openMVS/wiki/Usage) documentation that explain possible command line arguments. If you are unable to figure out what's wrong you could also try posting your question to OpenMVG or OpenMVS project issues list.

**Comment by huikang** [comment]
@rennu , thanks. I also found the explanation is here: https://github.com/openMVG/openMVG/issues/1325#issuecomment-394583338

Do you think it make sense to provide the default intrinsic value in the pipeline if openMVG can not derive from its database?

**Comment by rennu** [comment]
As of now there is no argument for default intrinsics in pipeline.py. You can provide pixel focal length using --flength, though.
